---
brew_tap:
  - caskroom/cask
  - caskroom/versions
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

brew_app:
  - ansible
  - docker
  - docker-compose
  - docker-machine
  - gettext
  - git-flow
  - go
  - go-app-engine-64
  - gauche
  - readline
  - typesafe-activator
  - wget

brew_cask:
  - android-studio
  - firefox
  - keepassx
  - messenger
  - intellij-idea-ce
  - visual-studio-code
  - emacs
  - atom
  - bathyscaphe
  - google-cloud-skd
  - googleappengine
  - google-chrome
